name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # Запускаем SUT
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов(должен быть обязательно)
      - name: Start SUT 1
        run: java -jar ./artifacts/app-mbank.jar &
      - name: Start SUT 2
        run: java -jar ./artifacts/app-order.jar -port=7777 &
      - name: Start SUT 3
        run: java -jar ./artifacts/app-card-delivery.jar -port=8080 &
      - name: Start SUT 4
        run: java -jar ./artifacts/app-callback.jar -port=8081 &
      - name: Start SUT 5
        run: java -jar ./artifacts/app-ibank-dom-modification.jar -port=8082 &
      - name: Start SUT 6
        run: java -jar ./artifacts/app-ibank-visibility.jar -port=8082 &

      - name: Build with Gradle
        run: ./gradlew test

# Команда `chmod +x gradlew` делает файл gradlew исполняемым в linux. 
# Команда `./gradlew test` собирает ваш проект и запускает тесты.

